services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-backend
    ports:
      - "8086:80"
    networks:
      - task-network

networks:
  task-network:
